# Generated by Django 4.1.7 on 2023-05-10 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_alter_user_table'),
        ('menu', '0006_alter_custommenu_status'),
        ('waiter', '0002_alter_table_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False, verbose_name='chave primaria id order')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantidade')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.custommenu', verbose_name='chave estrangeira prato')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waiter.table')),
                ('waiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='chave estrangeira garçom')),
            ],
            options={
                'db_table': 'table_orders',
                'managed': True,
            },
        ),
    ]
