# Generated by Django 4.1.7 on 2023-05-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PRONTO', 'Pronto'), ('EM PREPARO', 'Em Preparo'), ('CANCELADO', 'Cancelado')], default='EM PREPARO', max_length=30),
        ),
    ]
