# Generated by Django 4.1.7 on 2023-05-12 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='dish_id',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='waiter_id',
            new_name='waiter',
        ),
    ]
