# Generated by Django 4.1.7 on 2023-05-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'managed': True, 'permissions': (('give_feedback', 'can feedback restaurant'),)},
        ),
    ]
