# Generated by Django 4.1.7 on 2023-05-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_orders_motivo de cancelamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='canceled_by',
        ),
        migrations.AddField(
            model_name='orders',
            name='motivo de cancelamento',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
