# Generated by Django 4.1.7 on 2023-05-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_orders_canceled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='motivo de cancelamento',
            field=models.CharField(default='', max_length=255),
        ),
    ]
