# Generated by Django 4.1.7 on 2023-05-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_orders_motivo de cancelamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='motivo de cancelamento',
        ),
        migrations.AddField(
            model_name='orders',
            name='canceled_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
