# Generated by Django 4.1.7 on 2023-05-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_orders_motivo de cancelamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='canceled_by',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
