# Generated by Django 4.1.7 on 2023-05-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('responsible_name', models.CharField(max_length=81, verbose_name='nome do responsavel da mesa')),
                ('table_number', models.CharField(max_length=81, verbose_name='numero que vai na mesa')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
