# Generated by Django 4.1.7 on 2023-05-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table='table_tables',
        ),
    ]
