# Generated by Django 4.1.7 on 2023-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_alter_table_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Se a mesa esta finalizada ou não'),
        ),
    ]
