# Generated by Django 4.1.7 on 2023-03-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.IntegerField(auto_created=True, db_index=True, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome do prato')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do prato')),
                ('descricao', models.TextField(verbose_name='descrição do prato')),
                ('foto', models.ImageField(upload_to='', verbose_name='foto do prato')),
                ('status', models.BooleanField(verbose_name='ativo ou inativo')),
            ],
        ),
    ]
