# Generated by Django 4.1.7 on 2023-04-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome do prato')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor do prato')),
                ('descricao', models.TextField(verbose_name='descrição do prato')),
                ('foto', models.ImageField(upload_to='', verbose_name='foto do prato')),
                ('status', models.BooleanField(verbose_name='ativo ou inativo')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
