# Generated by Django 4.1.7 on 2023-04-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_custommenu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommenu',
            name='status',
            field=models.CharField(max_length=10, verbose_name='ativo ou inativo'),
        ),
    ]
