# Generated by Django 4.1.7 on 2023-05-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_custommenu_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='custommenu',
            table='table_menu',
        ),
    ]
