# Generated by Django 4.1.7 on 2023-03-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_id_alter_user_numero_celular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(default='', max_length=81, verbose_name='user'),
            preserve_default=False,
        ),
    ]
