# Generated by Django 4.1.7 on 2023-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_options_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Garçom', 'Garcom'), ('Cozinheiro', 'Cozinheiro'), ('Administrador', 'Administrador'), ('Operador de Caixa', 'Operador De Caixa'), ('Outro', 'Outro')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
