# Generated by Django 4.1.7 on 2023-05-08 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_cpf'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='table_user',
        ),
    ]
