# Generated by Django 4.1.7 on 2023-05-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(default='1900-10-10', verbose_name='data de nascimento'),
        ),
    ]
