# Generated by Django 4.1.7 on 2023-05-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user user', 'verbose_name_plural': 'users'},
        ),
    ]
