# Generated by Django 4.1.7 on 2023-05-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_options'),
    ]

    operations = [
    ]
