# Generated by Django 4.1.7 on 2023-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20230515_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Garçom', 'Garcom'), ('Cozinheiro', 'Cozinheiro'), ('Administrador', 'Administrador'), ('Outro', 'Outro')], max_length=30),
        ),
    ]
