# Generated by Django 4.1.7 on 2023-06-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_sales'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sales',
            table='Sales',
        ),
    ]
